description "Start Kindle billboard poller on boot"

start on started framework
stop on stopping framework

task

script
  if [ -f /mnt/us/billboard/autostart.sh ]; then
    [ -x /mnt/us/billboard/autostart.sh ] || chmod +x /mnt/us/billboard/autostart.sh
    /bin/sh /mnt/us/billboard/autostart.sh
  fi
end script
